/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pa.althaus.dam.javaproyect.aeropuerto.view.panels;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.util.HashMap;
import pa.althaus.dam.javaproyect.aeropuerto.controller.ProximosVuelosController;
import pa.althaus.dam.javaproyect.aeropuerto.model.DailyFlight;
import pa.althaus.dam.javaproyect.aeropuerto.model.dao.DailyFlightDao;

public class VuelosPrevistosPanel extends javax.swing.JPanel {
    private final ProximosVuelosController vuelosController;

    public VuelosPrevistosPanel() {
        initComponents();
        vuelosController = new ProximosVuelosController(new DailyFlightDao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrevistos = new javax.swing.JLabel();
        tblPrevistos = new javax.swing.JScrollPane();
        tblLlegadasDatos = new javax.swing.JTable();
        btnEnviar2 = new javax.swing.JButton();
        airportSelector = new javax.swing.JComboBox<>();

        lblPrevistos.setText("Vuelos previstos en los próximos 7 días");

        tblPrevistos.setViewportView(tblLlegadasDatos);

        btnEnviar2.setText("Enviar");
        btnEnviar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviar2ActionPerformed(evt);
            }
        });

        airportSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblPrevistos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(airportSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnEnviar2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblPrevistos)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblPrevistos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblPrevistos, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar2)
                    .addComponent(airportSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviar2ActionPerformed
       try {
            // Obtener el destino seleccionado
            String destino = (String) airportSelector.getSelectedItem();

            // Obtener vuelos previstos para el destino seleccionado
            HashMap<Integer, DailyFlight> vuelosPrevistos = vuelosController.getVuelosProximos(destino);

            // Mostrar vuelos previstos en la tabla
            actualizarTablaVuelosPrevistos(vuelosPrevistos);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al obtener los vuelos previstos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviar2ActionPerformed

    private void actualizarTablaVuelosPrevistos(HashMap<Integer, DailyFlight> vuelosPrevistos) {
        try {
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.addColumn("Código Vuelo Diario");
            tableModel.addColumn("Fecha Vuelo");
            tableModel.addColumn("Hora Salida");
            tableModel.addColumn("Hora Llegada");

            // Llenar la tabla con los datos de vuelos previstos
            for (DailyFlight dailyFlight : vuelosPrevistos.values()) {
                Object[] rowData = {
                        dailyFlight.getCodigoVueloDiario(),
                        dailyFlight.getFechaVuelo(),
                        dailyFlight.getHoraSalida(),
                        dailyFlight.getHoraLlegada()
                };
                tableModel.addRow(rowData);
            }

            tblLlegadasDatos.setModel(tableModel);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al actualizar la tabla de vuelos previstos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> airportSelector;
    private javax.swing.JButton btnEnviar2;
    private javax.swing.JLabel lblPrevistos;
    private javax.swing.JTable tblLlegadasDatos;
    private javax.swing.JScrollPane tblPrevistos;
    // End of variables declaration//GEN-END:variables
}
