/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pa.cifaviles.dam.diact1_2;

/**
 *
 * @author samuelaa
 */
public class FrmAlumno extends javax.swing.JFrame {

    /**
     * Creates new form FrmAlumno
     */
    public FrmAlumno() {
        initComponents();
        this.setLocationRelativeTo(null);
        ErrorMsg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBtn = new javax.swing.JPanel();
        ErrorMsg = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        pnlLbl = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblAlumJvn = new javax.swing.JLabel();
        pnlImputs = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        lblJvnName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        setIconImages(null);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 400));

        ErrorMsg.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        ErrorMsg.setForeground(new java.awt.Color(255, 51, 51));
        ErrorMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ErrorMsg.setText("hide");

        btnAdd.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnAdd.setText("Añadir");
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnLayout = new javax.swing.GroupLayout(pnlBtn);
        pnlBtn.setLayout(pnlBtnLayout);
        pnlBtnLayout.setHorizontalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBtnLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 104, Short.MAX_VALUE))
            .addGroup(pnlBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ErrorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBtnLayout.setVerticalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ErrorMsg)
                .addGap(10, 10, 10)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtTitle.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        txtTitle.setText("Nuevo Alumno");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(txtTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlLbl.setLayout(new java.awt.GridLayout(6, 0, 20, 20));

        lblNombre.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre");
        pnlLbl.add(lblNombre);

        lblapellido.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblapellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblapellido.setText("Apellidos");
        pnlLbl.add(lblapellido);

        lblEmail.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email");
        pnlLbl.add(lblEmail);

        lblEdad.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblEdad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEdad.setText("Edad");
        pnlLbl.add(lblEdad);

        lblTelefono.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTelefono.setText("Telefono");
        pnlLbl.add(lblTelefono);

        lblAlumJvn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblAlumJvn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlumJvn.setText("Alumno más joven:");
        pnlLbl.add(lblAlumJvn);

        pnlImputs.setMinimumSize(new java.awt.Dimension(200, 185));
        pnlImputs.setLayout(new java.awt.GridLayout(6, 0, 0, 20));

        txtNombre.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setAutoscrolls(false);
        pnlImputs.add(txtNombre);

        txtApellido.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlImputs.add(txtApellido);

        txtEmail.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlImputs.add(txtEmail);

        txtEdad.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtEdad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlImputs.add(txtEdad);

        txtTelefono.setColumns(2);
        txtTelefono.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlImputs.add(txtTelefono);

        lblJvnName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblJvnName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlImputs.add(lblJvnName);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pnlLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlImputs, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlImputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        if (Principal.cont < Principal.alumnos.length) {
            String nombre = txtNombre.getText();
            String apellidos = txtApellido.getText();
            String email = txtEmail.getText();
            String telefono = txtTelefono.getText();
            int edad;

            try {
                edad = Integer.parseInt(txtEdad.getText());
                ErrorMsg.setVisible(false);
            } catch (NumberFormatException e) {
                ErrorMsg.setText("La edad introducidad debe ser un número");
                ErrorMsg.setVisible(true);
                return;
            }

            Alumno nuevoAlumno = new Alumno(nombre, apellidos, email, telefono, edad);

            if (alumnoDuplicado(nuevoAlumno)) {
                ErrorMsg.setText("Error. El alumno ya existe");
                ErrorMsg.setVisible(true);
            } else {
                Principal.alumnos[Principal.cont] = nuevoAlumno;
                Principal.cont++;
            }

            String alumnoJoven = obtenerAlumnoMasJoven();
            lblJvnName.setText(alumnoJoven);

        } else {
            ErrorMsg.setText("Error. No se pueden añadir más de 5 alumnos");
            ErrorMsg.setVisible(true);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private String obtenerAlumnoMasJoven() {

        int menorEdad = Integer.MAX_VALUE;
        String nombreAlumno = "";

        for (int i = 0; i < Principal.cont; i++) {
            if (Principal.alumnos[i].getEdad() < menorEdad) {
                menorEdad = Principal.alumnos[i].getEdad();
                nombreAlumno = Principal.alumnos[i].getNombre() + " " + Principal.alumnos[i].getApellidos();
            }
        }
        return nombreAlumno;
    }

    private boolean alumnoDuplicado(Alumno nuevoAlumno) {

        for (int i = 0; i < Principal.cont; i++) {
            Alumno alumnoExistente = Principal.alumnos[i];

            if (alumnoExistente != null
                    && alumnoExistente.getNombre().equals(nuevoAlumno.getNombre())
                    && alumnoExistente.getApellidos().equals(nuevoAlumno.getApellidos())
                    && alumnoExistente.getEmail().equals(nuevoAlumno.getEmail())
                    && alumnoExistente.getTelefono().equals(nuevoAlumno.getTelefono())) {
                return true;
            }
        }
        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorMsg;
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel lblAlumJvn;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblJvnName;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JPanel pnlBtn;
    private javax.swing.JPanel pnlImputs;
    private javax.swing.JPanel pnlLbl;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables

}
