CREATE TABLE [dbo].[Usuarios]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[UserName] VARCHAR(50) NOT NULL UNIQUE,
	[Password] VARCHAR(50) NOT NULL,
	[Nombre] VARCHAR(50) NULL,
	[Email] VARCHAR(50) NULL,
	[FechaRegistro] DATE NOT NULL DEFAULT GETDATE(),
	DeletedBy INT,
	Deleted BIT NOT NULL DEFAULT(0)
)