/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pa.althaus.dam.javaproyect.aeropuerto.view;

import pa.althaus.dam.javaproyect.aeropuerto.view.*;

import java.awt.CardLayout;
import java.awt.Dimension;

import pa.althaus.dam.javaproyect.aeropuerto.controller.HelpService;

import static pa.althaus.dam.javaproyect.aeropuerto.util.Constants.FRAME_HEIGHT;
import static pa.althaus.dam.javaproyect.aeropuerto.util.Constants.FRAME_WIDTH;

import pa.althaus.dam.javaproyect.aeropuerto.view.panels.*;
import pa.althaus.dam.javaproyect.aeropuerto.view.panels.HomePanel;
import pa.althaus.dam.javaproyect.aeropuerto.view.panels.LlegadasPanel;
import pa.althaus.dam.javaproyect.aeropuerto.view.panels.RecaudacionesPanel;
import pa.althaus.dam.javaproyect.aeropuerto.view.panels.SalidasPanel;
import pa.althaus.dam.javaproyect.aeropuerto.view.panels.VuelosPorCompaniaPanel;
import pa.althaus.dam.javaproyect.aeropuerto.view.panels.VuelosPrevistosPanel;

/**
 * @author Imper
 */
public class AppFrame2 extends javax.swing.JFrame {

    private HelpService helpService;

    /**
     * Creates new form AppFrame
     */
    public AppFrame2() {
        initComponents();
        startUp();

    }

    private void startUp() {
        card = (CardLayout) container.getLayout();

        // Crear y agregar los paneles
        container.add(new HomePanel(), "Home");  // Agregar el menú como "Menu"
        container.add(new SalidasPanel(), "Salidas");
        container.add(new LlegadasPanel(), "Llegadas");
        container.add(new VuelosPorCompaniaPanel(), "VuelosPorCompania");
        container.add(new RecaudacionesPanel(), "Recaudaciones");
        container.add(new VuelosPrevistosPanel(), "VuelosPrevistos");

        card.show(container, "Home");
        helpService = new HelpService();
        helpService.setHelp(this, "https://s-althauss-organization.gitbook.io/aeropuerto/");

        setSize(FRAME_WIDTH, FRAME_HEIGHT);
        setLocationRelativeTo(null);

        // Establecer tamaño relativo del menú
        menu.setPreferredSize(new Dimension(FRAME_WIDTH / 6, FRAME_HEIGHT));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card = new java.awt.CardLayout();
        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalidas = new javax.swing.JButton();
        btnLlegadas = new javax.swing.JButton();
        btnCompany = new javax.swing.JButton();
        btnRecaudacion = new javax.swing.JButton();
        btnPrevistos = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        menu.setBackground(new java.awt.Color(60, 62, 65));
        menu.setMinimumSize(new java.awt.Dimension(0, 0));
        menu.setPreferredSize(new java.awt.Dimension(130, 80));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20);
        flowLayout1.setAlignOnBaseline(true);
        menu.setLayout(flowLayout1);

        jLabel1.setText("MENU");
        menu.add(jLabel1);

        btnSalidas.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnSalidas.setText("Salidas");
        btnSalidas.setMaximumSize(new java.awt.Dimension(120, 30));
        btnSalidas.setMinimumSize(new java.awt.Dimension(120, 30));
        btnSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidasActionPerformed(evt);
            }
        });
        menu.add(btnSalidas);

        btnLlegadas.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnLlegadas.setText("Llegadas");
        btnLlegadas.setMaximumSize(new java.awt.Dimension(120, 30));
        btnLlegadas.setMinimumSize(new java.awt.Dimension(120, 30));
        btnLlegadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlegadasActionPerformed(evt);
            }
        });
        menu.add(btnLlegadas);

        btnCompany.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnCompany.setText("Compañia");
        btnCompany.setMaximumSize(new java.awt.Dimension(120, 30));
        btnCompany.setMinimumSize(new java.awt.Dimension(120, 30));
        btnCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompanyActionPerformed(evt);
            }
        });
        menu.add(btnCompany);

        btnRecaudacion.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnRecaudacion.setText("Recaudacion");
        btnRecaudacion.setMaximumSize(new java.awt.Dimension(120, 30));
        btnRecaudacion.setMinimumSize(new java.awt.Dimension(120, 30));
        btnRecaudacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecaudacionActionPerformed(evt);
            }
        });
        menu.add(btnRecaudacion);

        btnPrevistos.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnPrevistos.setText("Previstos");
        btnPrevistos.setMaximumSize(new java.awt.Dimension(120, 30));
        btnPrevistos.setMinimumSize(new java.awt.Dimension(120, 30));
        btnPrevistos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevistosActionPerformed(evt);
            }
        });
        menu.add(btnPrevistos);

        btnAyuda.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnAyuda.setText("Ayuda");
        btnAyuda.setMaximumSize(new java.awt.Dimension(120, 30));
        btnAyuda.setMinimumSize(new java.awt.Dimension(120, 30));
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        menu.add(btnAyuda);

        getContentPane().add(menu, java.awt.BorderLayout.WEST);

        container.setLayout(new java.awt.CardLayout());
        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidasActionPerformed
        card.show(container, "Salidas");
    }//GEN-LAST:event_btnSalidasActionPerformed

    private void btnLlegadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlegadasActionPerformed
        card.show(container, "Llegadas");
    }//GEN-LAST:event_btnLlegadasActionPerformed

    private void btnCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompanyActionPerformed
        card.show(container, "VuelosPorCompania");
    }//GEN-LAST:event_btnCompanyActionPerformed

    private void btnRecaudacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecaudacionActionPerformed
        card.show(container, "Recaudaciones");
    }//GEN-LAST:event_btnRecaudacionActionPerformed

    private void btnPrevistosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevistosActionPerformed
        card.show(container, "VuelosPrevistos");
    }//GEN-LAST:event_btnPrevistosActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        helpService.openWebView("https://s-althauss-organization.gitbook.io/aeropuerto/");
    }//GEN-LAST:event_btnAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnCompany;
    private javax.swing.JButton btnLlegadas;
    private javax.swing.JButton btnPrevistos;
    private javax.swing.JButton btnRecaudacion;
    private javax.swing.JButton btnSalidas;
    private java.awt.CardLayout card;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
