/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pa.althaus.dam.javaproyect.aeropuerto.view;

import java.awt.CardLayout;
import javax.swing.JPanel;
import pa.althaus.dam.javaproyect.aeropuerto.view.panels.*;

/**
 *
 * @author Imper
 */
public class MainView extends javax.swing.JFrame {

    private JPanel mainPanel;
    private JPanel salidasPanel;
    private JPanel llegadasPanel;
    private JPanel vuelosPorCompaniaPanel;
    private JPanel recaudacionesPanel;
    private JPanel vuelosPrevistosPanel;
    
    
    public MainView() {
        initComponents();
        initPanels();
    }
    
    private void initPanels(){
        mainPanel = new MainPanel();
        salidasPanel = new SalidasPanel();
        llegadasPanel = new LlegadasPanel();
        vuelosPorCompaniaPanel = new VuelosPorCompaniaPanel();
        recaudacionesPanel = new RecaudacionesPanel();
        vuelosPrevistosPanel = new VuelosPrevistosPanel();

        mainPanel.add(salidasPanel, "Salidas");
        mainPanel.add(llegadasPanel, "Llegadas");
        mainPanel.add(vuelosPorCompaniaPanel, "VuelosPorCompania");
        mainPanel.add(recaudacionesPanel, "Recaudaciones");
        mainPanel.add(vuelosPrevistosPanel, "VuelosPrevistos");

        getContentPane().add(mainPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pa.althaus.dam.javaproyect.aeropuerto.view.panels.MainPanel mainPanel1 = new pa.althaus.dam.javaproyect.aeropuerto.view.panels.MainPanel();
        pa.althaus.dam.javaproyect.aeropuerto.view.panels.SalidasPanel salidasPanel1 = new pa.althaus.dam.javaproyect.aeropuerto.view.panels.SalidasPanel();
        pa.althaus.dam.javaproyect.aeropuerto.view.panels.LlegadasPanel llegadasPanel1 = new pa.althaus.dam.javaproyect.aeropuerto.view.panels.LlegadasPanel();
        pa.althaus.dam.javaproyect.aeropuerto.view.panels.VuelosPorCompaniaPanel vuelosPorCompaniaPanel1 = new pa.althaus.dam.javaproyect.aeropuerto.view.panels.VuelosPorCompaniaPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor Aeropuerto");
        setBackground(new java.awt.Color(60, 63, 64));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(mainPanel1, "card2");
        getContentPane().add(salidasPanel1, "card4");
        getContentPane().add(llegadasPanel1, "card3");
        getContentPane().add(vuelosPorCompaniaPanel1, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
