/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pa.althaus.dam.vitp.stacktest.components;

/**
 *
 * @author samuelaa
 */
public class DlgRegistroStack extends javax.swing.JDialog {

    /**
     * Creates new form DlgRegistroStack
     */
    public DlgRegistroStack(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdentificador = new javax.swing.JLabel();
        lblIdResult = new javax.swing.JLabel();
        lblFechaCreacion = new javax.swing.JLabel();
        lblFechaResult = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblTituloResult = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblAutorResult = new javax.swing.JLabel();
        lblURL = new javax.swing.JLabel();
        lblURLResult = new javax.swing.JLabel();
        lblRespuesta = new javax.swing.JLabel();
        checkResult = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(6, 3, 20, -20));

        lblIdentificador.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdentificador.setText("Identificador:");
        getContentPane().add(lblIdentificador);

        lblIdResult.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIdResult.setText("ID");
        getContentPane().add(lblIdResult);

        lblFechaCreacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaCreacion.setText("Fecha de Creación:");
        getContentPane().add(lblFechaCreacion);

        lblFechaResult.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFechaResult.setText("fecha de creacion");
        getContentPane().add(lblFechaResult);

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTitulo.setText("Titulo");
        getContentPane().add(lblTitulo);

        lblTituloResult.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloResult.setText("titulo");
        getContentPane().add(lblTituloResult);

        lblAutor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAutor.setText("Autor:");
        getContentPane().add(lblAutor);

        lblAutorResult.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAutorResult.setText("autor");
        getContentPane().add(lblAutorResult);

        lblURL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblURL.setText("URL:");
        getContentPane().add(lblURL);

        lblURLResult.setForeground(java.awt.Color.BLUE);
        lblURLResult.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblURLResult.setText("url");
        lblURLResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblURLResultMouseClicked(evt);
            }
        });
        getContentPane().add(lblURLResult);

        lblRespuesta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRespuesta.setText("Con Respuesta");
        getContentPane().add(lblRespuesta);
        getContentPane().add(checkResult);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblURLResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblURLResultMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblURLResultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgRegistroStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgRegistroStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgRegistroStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgRegistroStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgRegistroStack dialog = new DlgRegistroStack(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkResult;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblAutorResult;
    private javax.swing.JLabel lblFechaCreacion;
    private javax.swing.JLabel lblFechaResult;
    private javax.swing.JLabel lblIdResult;
    private javax.swing.JLabel lblIdentificador;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloResult;
    private javax.swing.JLabel lblURL;
    private javax.swing.JLabel lblURLResult;
    // End of variables declaration//GEN-END:variables
}
