/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pa.althaus.dam.vitp.stacktest.components;

import java.util.ArrayList;
import com.mashape.unirest.http.JsonNode;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.io.Serializable;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author samuelaa
 */
public class StackOverFlowSearch extends javax.swing.JPanel implements Serializable {

    ArrayList<RegistroStack> lstRegistros = new ArrayList<>();

    /**
     * Creates new form StackOverflowSearch
     */
    public StackOverFlowSearch() {
        initComponents();
    }

    private void serviceSearch(String text) throws UnirestException {
        long toDate = System.currentTimeMillis() / 1000;
        long diferencia = 31560000L;
        long fromDate = toDate - diferencia;
        HttpResponse<JsonNode> jsonResponse
                = Unirest.get("https://api.stackexchange.com/2.3/search")
                        .header("accept", "application/json")
                        .queryString("page", "1")
                        .queryString("pagesize", "10")
                        .queryString("fromdate", fromDate)
                        .queryString("todate", toDate)
                        .queryString("order", "desc")
                        .queryString("sort", "creation")
                        .queryString("tagged", text)
                        .queryString("site", "stackoverflow")
                        .asJson();

        JSONObject jn = jsonResponse.getBody().getObject();
        JSONArray itemsArray = jn.getJSONArray("items");
        lstRegistros.clear();
        for (int x = 0; x < itemsArray.length(); x++) {
            JSONObject currentItem = itemsArray.getJSONObject(x);
            JSONObject owner = currentItem.getJSONObject("owner");
            RegistroStack currentRegStack = new RegistroStack(currentItem.getInt("question_id"),
                    new Date(currentItem.getLong("creation_date") * 1000),
                    currentItem.getString("title"),
                    owner.getString("display_name"),
                    currentItem.getBoolean("is_answered"),
                    currentItem.getString("link"));
            lstRegistros.add(currentRegStack);
        }
        StackTableModel tbModel = new StackTableModel(lstRegistros);
        this.tblResultados.setModel(tbModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        lblError = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 38, 284, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 38, -1, -1));

        tblResultados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblResultados);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 79, 729, 495));

        lblError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setText("Error no Controlado");
        add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 592, 253, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        if (txtBusqueda.getText().isBlank()) {
            lblError.setVisible(true);
            lblError.setText("Por favor, introduzca un patrón de búsqueda");
        } else if (txtBusqueda.getText().contains(" ")) {
            lblError.setVisible(true);
            lblError.setText("Por favor, introduzca únicamente una palabra");
        } else {
            try {
                serviceSearch(txtBusqueda.getText());
                lblError.setVisible(false);
            } catch (UnirestException ex) {
                Logger.getLogger(StackOverFlowSearch.class.getName()).log(Level.SEVERE, null, ex);
                lblError.setText("Error en petición al servicio: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
