CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(50) NOT NULL,
	[Surname] VARCHAR(50) NOT NULL,
	[UserType] VARCHAR(50) NOT NULL,
	[UserName] VARCHAR(50) NOT NULL UNIQUE,
	[Password] VARCHAR(MAX) NOT NULL,
	Deleted BIT NOT NULL DEFAULT(0)
)
