CREATE TABLE [dbo].[Users]
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    UserName NVARCHAR(255) NOT NULL,
    Name NVARCHAR(255) NOT NULL,
    Surname NVARCHAR(255) NOT NULL,    
    UserType NVARCHAR(50) NOT NULL,
    CreatedAt DATE NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATE NULL,
    UpdatedBy INT NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    DeletedAt DATE NULL,
    DeletedBy INT NULL
)
